name: CI

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Berlin
      - name: Run unit tests
        run: npm run test:unit:coverage
        env:
          FORCE_COLOR: 1
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: target/coverage/coverage-final.json
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Check source code
        run: |
          npm run lint
          npm run copy:paste:detection
      - name: Compile source code
        run: npm run compile
      - name: Upload compiled source code as artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-source-node-${{ matrix.node-version }}
          path: target/src/
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Berlin
      - name: Run integration tests
        run: npm run test:integration
        env:
          FORCE_COLOR: 1
      - name: Run mutation tests
        run: npm run test:unit:mutation
  release:
    if: github.ref == 'refs/heads/main'
    needs: [commitlint, code-coverage, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Download compiled source code artifact
        uses: actions/download-artifact@v2
        with:
          name: compiled-source-node-16
          path: target/src/
      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
